"""Render a LearningPack to a self-contained static HTML learning page.

Output layout::

    out_dir/
      index.html
      manifest.json
      audio/
        001.wav
        002.wav
        …
      assets/          # reserved for future images, fonts
"""

from __future__ import annotations

import html
import json
from pathlib import Path
from typing import Any

from sanskrit_reciter.learning.models import Annotation, LearningPack, VerseUnit


def write_html_pack(pack: LearningPack, out_dir: str | Path) -> Path:
    """Write index.html + manifest.json under out_dir. Returns index path."""
    root = Path(out_dir)
    root.mkdir(parents=True, exist_ok=True)
    (root / "audio").mkdir(exist_ok=True)
    (root / "assets").mkdir(exist_ok=True)

    manifest_path = root / "manifest.json"
    manifest_path.write_text(
        json.dumps(pack.to_dict(), ensure_ascii=False, indent=2),
        encoding="utf-8",
    )

    index = root / "index.html"
    index.write_text(_render_document(pack), encoding="utf-8")
    return index


def _esc(s: str | None) -> str:
    return html.escape(s or "", quote=True)


def _render_document(pack: LearningPack) -> str:
    verses_html = "\n".join(_render_verse(v) for v in pack.verses)
    n_ok = sum(1 for v in pack.verses if v.audio and not v.error)
    n_fail = sum(1 for v in pack.verses if v.error)
    subtitle = f"<p class='subtitle'>{_esc(pack.subtitle)}</p>" if pack.subtitle else ""
    desc = (
        f"<p class='description'>{_esc(pack.description)}</p>" if pack.description else ""
    )
    stats = f"{len(pack.verses)} śloka(s) · {n_ok} with audio"
    if n_fail:
        stats += f" · {n_fail} failed"

    return f"""<!DOCTYPE html>
<html lang="sa">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>{_esc(pack.title)}</title>
  <style>
{_CSS}
  </style>
</head>
<body>
  <header class="pack-header">
    <h1>{_esc(pack.title)}</h1>
    {subtitle}
    {desc}
    <p class="stats">{_esc(stats)}</p>
    <nav class="toolbar">
      <button type="button" id="btn-play-all" class="btn">▶ Play all</button>
      <button type="button" id="btn-stop" class="btn btn-ghost">■ Stop</button>
      <label class="toggle"><input type="checkbox" id="auto-advance" checked /> Auto-advance</label>
    </nav>
  </header>

  <main class="verse-list" id="verse-list">
{verses_html}
  </main>

  <footer class="pack-footer">
    <p>Generated by SanskritReciter · audio via Vāgdhenu · offline learning pack</p>
    <p class="hint">Future annotations (anvaya, pratipadārtha, grammar, …) appear under each śloka when provided.</p>
  </footer>

  <script>
{_JS}
  </script>
</body>
</html>
"""


def _render_verse(v: VerseUnit) -> str:
    text_html = "<br />\n".join(_esc(line) for line in v.text.splitlines() if line.strip()) or _esc(
        v.text
    )
    ref = f'<span class="ref">{_esc(v.source_ref)}</span>' if v.source_ref else ""
    meter = f'<span class="meter">{_esc(v.meter)}</span>' if v.meter else ""
    meta_bits = " ".join(x for x in (ref, meter) if x)

    if v.audio:
        audio_html = f"""
      <div class="audio-block">
        <audio id="audio-{_esc(v.id)}" class="verse-audio" controls preload="none" src="{_esc(v.audio)}"></audio>
      </div>"""
    elif v.error:
        audio_html = f'<p class="audio-error">Audio unavailable: {_esc(v.error)}</p>'
    else:
        audio_html = '<p class="audio-missing">No audio</p>'

    anns = [_render_annotation(a) for a in v.annotations]
    # Placeholder slots signal extensibility even when empty (collapsed via CSS if empty container)
    annotations_html = ""
    if anns:
        annotations_html = (
            '<section class="annotations" aria-label="Annotations">\n'
            + "\n".join(anns)
            + "\n      </section>"
        )
    else:
        annotations_html = (
            '<section class="annotations annotations-empty" '
            'data-placeholder="annotations" hidden></section>'
        )

    err_class = " verse-error" if v.error and not v.audio else ""
    return f"""
    <article class="verse{err_class}" id="v-{_esc(v.id)}" data-verse-id="{_esc(v.id)}" data-index="{v.index}">
      <header class="verse-header">
        <span class="num">{v.index}</span>
        {meta_bits}
      </header>
      <div class="sloka-text" lang="sa">{text_html}</div>
      {audio_html}
      {annotations_html}
    </article>"""


def _render_annotation(a: Annotation) -> str:
    kind = _esc(a.kind)
    title = _esc(a.display_title())
    body = _render_content(a)
    return f"""
        <div class="annotation" data-kind="{kind}">
          <h3 class="ann-title">{title}</h3>
          <div class="ann-body">{body}</div>
        </div>"""


def _render_content(a: Annotation) -> str:
    content = a.content
    mode = (a.render or "auto").lower()

    if content is None:
        return ""

    if mode == "hidden":
        return ""

    # Structured pratipada / table rows
    if mode == "table" or (
        mode == "auto" and isinstance(content, list) and content and isinstance(content[0], dict)
    ):
        return _render_table(content)

    if mode == "list" or (mode == "auto" and isinstance(content, list) and all(isinstance(x, str) for x in content)):
        items = "".join(f"<li>{_esc(str(x))}</li>" for x in content)
        return f"<ul>{items}</ul>"

    if isinstance(content, dict):
        # key → value prose
        rows = "".join(
            f"<tr><th>{_esc(str(k))}</th><td>{_esc(str(v))}</td></tr>"
            for k, v in content.items()
        )
        return f'<table class="kv">{rows}</table>'

    # default: prose, preserve newlines
    text = str(content)
    return "<p>" + "<br />\n".join(_esc(line) for line in text.splitlines()) + "</p>"


def _render_table(rows: Any) -> str:
    if not isinstance(rows, list) or not rows:
        return ""
    # Collect column keys from first dict-ish rows
    keys: list[str] = []
    for row in rows:
        if isinstance(row, dict):
            for k in row.keys():
                if k not in keys:
                    keys.append(str(k))
    if not keys:
        return ""
    # Friendly Sanskrit learning defaults
    header_labels = {
        "pada": "पद",
        "artha": "अर्थ (EN)",
        "hindi": "अर्थ (HI)",
        "morph": "रूप / विभक्ति",
        "kaaraka": "कारक",
        "sandhi": "सन्धि-रूप",
        "samasa": "समास",
        "vibhakti": "विभक्ति",
        "linga": "लिङ्ग",
        "root": "धातु",
        "form": "रूप",
        "note": "टिप्पणी",
    }
    thead = "".join(f"<th>{_esc(header_labels.get(k, k))}</th>" for k in keys)
    body_rows = []
    for row in rows:
        if not isinstance(row, dict):
            continue
        tds = "".join(f"<td>{_esc(str(row.get(k, '')))}</td>" for k in keys)
        body_rows.append(f"<tr>{tds}</tr>")
    return f'<table class="data"><thead><tr>{thead}</tr></thead><tbody>{"".join(body_rows)}</tbody></table>'


_CSS = """
  :root {
    --bg: #f7f3ea;
    --card: #fffdf7;
    --ink: #1c1917;
    --muted: #78716c;
    --accent: #9a3412;
    --line: #e7e0d2;
    --audio-bg: #f5efe3;
    --ann-bg: #faf6ef;
    --radius: 14px;
    --font-sa: "Noto Serif Devanagari", "Devanagari MT", "Arial Unicode MS", serif;
    --font-ui: "Source Sans 3", "Segoe UI", system-ui, sans-serif;
  }
  * { box-sizing: border-box; }
  body {
    margin: 0;
    background: radial-gradient(1200px 600px at 10% -10%, #fff8e7, transparent),
                radial-gradient(900px 500px at 100% 0%, #f0e6d4, transparent),
                var(--bg);
    color: var(--ink);
    font-family: var(--font-ui);
    line-height: 1.55;
  }
  .pack-header, .pack-footer, .verse-list {
    width: min(820px, calc(100% - 2rem));
    margin-left: auto;
    margin-right: auto;
  }
  .pack-header {
    padding: 2.2rem 0 1rem;
  }
  .pack-header h1 {
    font-family: var(--font-sa);
    font-weight: 600;
    font-size: clamp(1.6rem, 3vw, 2.1rem);
    margin: 0 0 0.35rem;
    color: var(--accent);
  }
  .subtitle { margin: 0.2rem 0; color: var(--muted); }
  .description { margin: 0.6rem 0 0; max-width: 60ch; }
  .stats { color: var(--muted); font-size: 0.92rem; margin: 0.75rem 0 1rem; }
  .toolbar { display: flex; flex-wrap: wrap; gap: 0.6rem; align-items: center; }
  .btn {
    border: 1px solid var(--accent);
    background: var(--accent);
    color: #fffaf3;
    border-radius: 999px;
    padding: 0.45rem 1rem;
    font: inherit;
    cursor: pointer;
  }
  .btn:hover { filter: brightness(1.05); }
  .btn-ghost {
    background: transparent;
    color: var(--accent);
  }
  .toggle { color: var(--muted); font-size: 0.92rem; display: flex; gap: 0.4rem; align-items: center; }
  .verse-list { display: flex; flex-direction: column; gap: 1rem; padding-bottom: 3rem; }
  .verse {
    background: var(--card);
    border: 1px solid var(--line);
    border-radius: var(--radius);
    padding: 1.1rem 1.2rem 1.15rem;
    box-shadow: 0 8px 24px rgba(68, 42, 12, 0.04);
  }
  .verse:target, .verse.playing {
    border-color: #d6a57a;
    box-shadow: 0 0 0 3px rgba(154, 52, 18, 0.08);
  }
  .verse-error { opacity: 0.85; }
  .verse-header {
    display: flex; align-items: center; gap: 0.6rem;
    margin-bottom: 0.55rem; color: var(--muted); font-size: 0.86rem;
  }
  .num {
    display: inline-flex; align-items: center; justify-content: center;
    min-width: 1.8rem; height: 1.8rem; border-radius: 999px;
    background: #f3e7d5; color: var(--accent); font-weight: 700; font-size: 0.85rem;
  }
  .ref, .meter { background: #f3eee4; padding: 0.1rem 0.45rem; border-radius: 6px; }
  .sloka-text {
    font-family: var(--font-sa);
    font-size: clamp(1.25rem, 2.4vw, 1.55rem);
    line-height: 1.85;
    margin: 0.2rem 0 0.85rem;
    white-space: normal;
  }
  .audio-block {
    background: var(--audio-bg);
    border-radius: 10px;
    padding: 0.55rem 0.7rem;
  }
  .verse-audio { width: 100%; height: 36px; }
  .audio-error, .audio-missing { color: #b45309; font-size: 0.9rem; margin: 0.4rem 0; }
  .annotations {
    margin-top: 0.9rem;
    display: flex; flex-direction: column; gap: 0.7rem;
  }
  .annotation {
    background: var(--ann-bg);
    border-left: 3px solid #d6a57a;
    border-radius: 0 10px 10px 0;
    padding: 0.65rem 0.85rem;
  }
  .ann-title {
    margin: 0 0 0.35rem;
    font-size: 0.92rem;
    color: var(--accent);
    letter-spacing: 0.01em;
  }
  .ann-body { font-size: 0.98rem; }
  .ann-body p { margin: 0.2rem 0; }
  .ann-body ul { margin: 0.2rem 0; padding-left: 1.2rem; }
  table.data, table.kv {
    width: 100%; border-collapse: collapse; font-size: 0.95rem;
  }
  table.data th, table.data td, table.kv th, table.kv td {
    border-bottom: 1px solid var(--line); padding: 0.35rem 0.4rem; text-align: left;
    vertical-align: top;
  }
  table.data th { color: var(--muted); font-weight: 600; }
  table.kv th { width: 30%; color: var(--muted); font-weight: 600; }
  .pack-footer {
    padding: 1rem 0 2.5rem; color: var(--muted); font-size: 0.85rem;
  }
  .pack-footer .hint { opacity: 0.85; }
  @media (max-width: 560px) {
    .pack-header, .pack-footer, .verse-list { width: calc(100% - 1.2rem); }
    .verse { padding: 0.95rem; }
  }
"""

_JS = """
  (function () {
    const players = () => Array.from(document.querySelectorAll('audio.verse-audio'));
    const autoAdv = () => document.getElementById('auto-advance')?.checked;

    function clearPlaying() {
      document.querySelectorAll('.verse.playing').forEach(el => el.classList.remove('playing'));
    }

    players().forEach((audio, idx, all) => {
      audio.addEventListener('play', () => {
        clearPlaying();
        audio.closest('.verse')?.classList.add('playing');
        all.forEach(a => { if (a !== audio) { a.pause(); } });
      });
      audio.addEventListener('ended', () => {
        audio.closest('.verse')?.classList.remove('playing');
        if (!autoAdv()) return;
        const next = all[idx + 1];
        if (next) {
          next.closest('.verse')?.scrollIntoView({ behavior: 'smooth', block: 'center' });
          next.play().catch(() => {});
        }
      });
      audio.addEventListener('pause', () => {
        if (audio.ended) return;
        // keep highlight only while actively playing
        if (audio.currentTime > 0 && !audio.paused) return;
      });
    });

    document.getElementById('btn-play-all')?.addEventListener('click', () => {
      const all = players();
      if (!all.length) return;
      all.forEach(a => { a.pause(); a.currentTime = 0; });
      all[0].closest('.verse')?.scrollIntoView({ behavior: 'smooth', block: 'center' });
      all[0].play().catch(() => {});
    });
    document.getElementById('btn-stop')?.addEventListener('click', () => {
      players().forEach(a => { a.pause(); });
      clearPlaying();
    });
  })();
"""
